<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Herrera.Data\Herrera.Data.csproj" />
    <ProjectReference Include="..\Herrera.Dominio\Herrera.Dominio.csproj" />
    <ProjectReference Include="..\Herrera.DTO\Herrera.DTO.csproj" />
  </ItemGroup>

</Project>
