<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.31" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Herrera.Data\Herrera.Data.csproj" />
    <ProjectReference Include="..\Herrera.Dominio\Herrera.Dominio.csproj" />
    <ProjectReference Include="..\Herrera.DTO\Herrera.DTO.csproj" />
    <ProjectReference Include="..\Herrera.Services\Herrera.Services.csproj" />
  </ItemGroup>

</Project>
